### ISSUE TITLE
need test case for content-type multipart/form-data

### ISSUE THREAD

**Issue by tjprescott** [Azure/cadl-ranch#156]
See issue:
https://github.com/Azure/cadl-azure/issues/1664

I'm assuming that since this needs special treatment in the autorest emitter, it would need special treatment in at least the Python emitter since it does not go through Autorest. But it should probably be a test case here to ensure that even the code generators that do leverage Autorest do this correctly, and it will be useful if they ever decide to divorce from Autorest to ensure this scenario is covered.

**Comment by lmazuel** [comment]
See https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIFR5cGVTcGVjLkh0dHA7CgpvcCB1cGxvYWRJbWFnZShAaGVhZGVyIGNvbnRlbnTELjogIm11bHRpcGFydC9mb3JtLWRhdGEiLCBAYm9keSBpxDg6IE3EI1BhcnRSZXF1ZXN0KTogdm9pZDsKCm1vZGVsIEFkZHJlc3MgewogIHN0cmVldDrECGluZzsKICBjaXR5yhB9CgpAZW5jb2RlKCJiaW5hcnkiKSAgLy8gU2VlIOQAznM6Ly9naXRodWIuY29tL21pY3Jvc29mdC%2FpAPRpc3N1ZXMvMjM3MApzY2FsYXIgxkogZXh0ZW5kcyBieXRlc%2BkAn%2FAAv%2BUAqGlk6QCUxH5GaWVsZCAiaWQiIGlzIHRleHQvcGxhaW4KICBh5gDeOugA58wwxxzFNWFuIGFwcGxpY2F0aW9uL2pzb24KCiAgcHJvZmlsZeUBgzrnAKk75QDyx0TMIcZJy0ZvY3RldC3kAVVhbcZOZXZpb3VzQcV4ZeoAlltd5QCYVGhpc8RET05FIOQB1SwgYXMgYSBKU09OIGFycmF5xUVpY3R1csQ95gCPzzxhcyBtYW55xUDEDW5lY2Vzc2FyeQogIOQBwAovKioKClBPU1QgL%2BYCYCBIVFRQLzEuMQpD5gJcLUxlbmd0aDogNDI4yRTmAnHzAnA7IGJvdW5kYXJ5PWFiY2RlMTIzNDUKCi0tyw7IRURpc3Bvc2nkAR06IMtCbmFtZT3kAcDPb%2BsBywoxMjNlNDU2Ny1lODliLTEyZDMtYTQ1Ni00MjY2NTU0NDAwMDDfdtV26AIGz3vyAg7kAnki5gMiIjogIjMsIEdhcmRlbiBTdCIsxBzkAyzEGkhpbGxzYmVyeSwgVVQiCn3%2FAJb1AJbsAlggIjsgxA3GGuUD1zEucG5n%2FACz7gJ7e%2BKApsRC6AQ%2B4oCm7gCWLS3%2FAJjqAJjuAsP%2FATduCgpb7wE4NDIsIEhpdGNoaGlrZXJz8QE%2BTmV3LVlvcmssIE5ZIgp9LM8%2FMjIsIEFjYWNpYSBBds46TG9uZG9uLCBVSyIKfV3%2FAXb2AN7nA1ztAXHHFf8Bc%2F8Bc%2FIBc%2F8Ak%2F8Ak8UVMv8Ak%2F8Ak%2FIAkwogKi8%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

and for reference 

https://swagger.io/docs/specification/describing-request-body/multipart-requests/

**Comment by qiaozha** [comment]
@lmazuel  Since openai is using multipart/form-data content type, should we prioritize this ?

**Comment by lirenhe** [comment]
@msyyc, please follow the above playground to add test in cadl-ranch

**Comment by msyyc** [comment]
Python azure-core doesn't support send request which contains multi files, so I use the following code to test new cadl-ranch case:
```python
import requests
import json

address = json.dumps({"city": "X"}, indent=2)
addresses = json.dumps([{"city": "Y"}, {"city": "Z"}], indent=2)
files = (
    ('id', (None, "123", "text/plane")),
    ('address', (None, address, "application/json")),
    ('addresses', (None, addresses, "application/json")),
    ('profileImage', ("image1.png", open("D:\\dev1\\cadl-ranch\\packages\\cadl-ranch-specs\\assets\\image.png", "rb"), "application/octet-stream")),
    ('pictures', ("pictures1.png", open("D:\\dev1\\cadl-ranch\\packages\\cadl-ranch-specs\\assets\\image.png", "rb"), "application/octet-stream")),
    ('pictures', ("pictures2.jpg", open("D:\\dev1\\cadl-ranch\\packages\\cadl-ranch-specs\\assets\\image.jpg", "rb"), "application/octet-stream")),
)
requests.post(url="http://127.0.0.1:3000/content-type/multipart-formdata", files=files)
```
