### ISSUE TITLE
models/usage, mockapi issue

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/cadl-ranch#157]
I found there are two issues in the [mockapi.ts](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/usage/mockapi.ts) of models/usage case.
1. The HTTP method of `Scenarios.Models_Usage_output` case shoud be ``get` instead of `post`. See [here](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/usage/main.cadl#L40-L43) for the corresponding cadl definition.
2. We defined the status code in the response as `202`, see [here](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/usage/mockapi.ts#L17), but the cadl definition does not indicate it will return `202`, so in our code, we are expecting status code `200` (the default one) instead of `202` like below. 
May I know the intention of making this call return `202`? Shall we still return `202` and modify the cadl definition or return `200` in mockapi.ts? 
```java
@Get("/models/usage/output")
@ExpectedResponses({200})
@UnexpectedResponseExceptionType(
        value = ClientAuthenticationException.class,
        code = {401})
@UnexpectedResponseExceptionType(
        value = ResourceNotFoundException.class,
        code = {404})
@UnexpectedResponseExceptionType(
        value = ResourceModifiedException.class,
        code = {409})
@UnexpectedResponseExceptionType(HttpResponseException.class)
Mono<Response<BinaryData>> output(
        @HeaderParam("accept") String accept, RequestOptions requestOptions, Context context);
```

**Comment by MaryGao** [comment]
Thanks for bringing this up! We also met these issues,

- For first one we should change from post to get 
https://github.com/Azure/cadl-ranch/blob/d1ffa96dc92bed37e96d05ca25cf204f2aa01b2d/packages/cadl-ranch-specs/http/models/usage/mockapi.ts#L16
- For second one the 200 should be more reasonable compared with 202
https://github.com/Azure/cadl-ranch/blob/d1ffa96dc92bed37e96d05ca25cf204f2aa01b2d/packages/cadl-ranch-specs/http/models/usage/mockapi.ts#L17

**Comment by lmazuel** [comment]
Bug fix has been merged, closing
