### ISSUE TITLE
Update to tests for extensible enums required

### ISSUE THREAD

**Issue by tjprescott** [Azure/cadl-ranch#158]
At a recent Cadl design meeting, we approved a design to simplify the way extensible enums work. This will require changing the tests in cadl-rach to force DPG emitters to update their behavior:

Here's the underlying Cadl issue:
https://github.com/Azure/cadl-azure/issues/2134

```

// Old gross behavior that we are currently enforcing
enum ThingKV{
  a;
  b;
}
@knownValues(ThingKV)
model Thing is string {};

// New hotness
enum Thing {
  a;
  b;
}
```

In the new behavior, all regular Cadl enums should be translated as extensible by emitters. The exception, where an enum is NOT extensible, will be denoted by the `@fixed` decorator:

```
@fixed
enum YesNo {
 yes;
 no;
}
```

**Comment by weidongxu-microsoft** [comment]
SDK will temporary disable tests on https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/extensible-enums/main.cadl#L9-L17 (which now being fixed enum, before this behavior change)

**Comment by tjprescott** [comment]
> SDK will temporary disable tests on https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/extensible-enums/main.cadl#L9-L17 (which now being fixed enum), before this behavior change.

@weidongxu-microsoft I don't understand this comment. The whole point of making the change to this test is so that emitters will begin failing the revised checks to ensure that all emitters are updated to generate extensible enums correctly.

**Comment by weidongxu-microsoft** [comment]
@tjprescott 
I didn't found the `@fixed` in microsoft/cadl. Just figured out it is in `Azure.Core`. Sure, will switch the behavior in emitter.
