### ISSUE TITLE
Need process to ensure cadl-ranch updates to latest cadl package versions

### ISSUE THREAD

**Issue by tjprescott** [Azure/cadl-ranch#170]
Right now the package.json for this repo is a version behind the latest releases. This highlights the need for a process to update these whenever a new Cadl is released.

**Comment by tjprescott** [comment]
Actually, I just needed to update my branch, so we aren't behind. I guess there is still the question of how we update these. Is it just ad-hoc or is there something that ensures we aren't lagging behind?

**Comment by timotheeguerin** [comment]
Going to close that as I think we have just been pretty good at keeping up to date and otherwise it can be the job of whomever wants to add a new feature that needs an update
