### ISSUE TITLE
issues met in models/visibility, projection and azure/core

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/cadl-ranch#189]
Hi @iscai-msft, @timotheeguerin 
I'm trying to integrate below three senarios in cadl-ranch, but found issues. Could you please take a look and udate the cadl-ranch code accordingly?
/cc @lmazuel 

1. models/visibility

* url used in cadl definition and mockapi.ts are not matching.

cadl definition is `/models/visibility`:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/visibility/main.cadl#L7
mockapi.t is `/models/visibility/automatic`:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/visibility/mockapi.ts#L24

2.  azure/core

* url used in cadl definition and mockapi.ts are not matching.

cadl definition is `/azure/core/users`:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/azure/core/main.cadl#L10-L13
mockapi.t is `/azure/core/`:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/azure/core/mockapi.ts#L7

* The name space is `_Specs_.Azure.Core`. Would like to understand why use "_", the underscore looks a bit strange.

3. projection

* property defined in cadl is different from mockapi.ts

cadl definition is `producedBy`
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/projection/main.cadl#L14
mockapi.ts is `codegen`：
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/projection/mockapi.ts#L8

**Comment by iscai-msft** [comment]
For `_Specs_.Azure.Core` I'm assuming this is so it doesn't conflict with the actual `Azure.Core` library. The other ones do seem like issues. I can take a look next week, but also feel free to submit a PR yourself and we can review it.

Also @timotheeguerin is out on parental leave for the next 2 months, you just need an approval for me or @lmazuel now

**Comment by haolingdong-msft** [comment]
Hi @iscai-msft, thanks a lot for your reply. I tried to update the url for `models/visibility` case, but met below issue.

The properties for model `VisibilityModel` are all required. But in mockapi.ts, it only accepts one property to be set. From my understanding, we should set values for all required property, **is this mockapi's bug as it only accepts one property to be set?**



PS: The problem in Java currently is when create `VisibilityModel`, we must set a `boolean` value for `deleteProp`, since `boolean` type can not be `null`. Then `getModel()` will have below error. 

```java
@JsonCreator
    public VisibilityModel(
            @JsonProperty(value = "queryProp", required = true) int queryProp,
            @JsonProperty(value = "createProp", required = true) List<String> createProp,
            @JsonProperty(value = "updateProp", required = true) List<Integer> updateProp,
            @JsonProperty(value = "deleteProp", required = true) boolean deleteProp) {
        this.queryProp = queryProp;
        this.createProp = createProp;
        this.updateProp = updateProp;
        this.deleteProp = deleteProp;
    }
```
```java
com.azure.core.exception.HttpResponseException: Status code 400, "{"message":"Body provided doesn't match expected body","expected":{"queryProp":123},"actual":{"queryProp":123,"deleteProp":false}}"
```

**Comment by haolingdong-msft** [comment]
Hi @lmazuel, also for models/visibility case, it has routing unmatch issue, but I saw you created pr to add this case  into python and the tests passed. I am curious on why the tests can pass. Will the tests pass if url is updated?https://github.com/Azure/autorest.python/pull/1630

**Comment by iscai-msft** [comment]
I believe this is by design, and this is where we get to the model being different based off of use cases. If you look at the visibility of these properties, they are used for specific contexts. For example, we have `visibility("create")`. These properties are only accepted on create calls, but they are required for them. Then, we also have `visiblity("delete")`, and here we only require these properties for delete calls.

I don't believe any language has a fully fleshed out approach to all of these various visibility options (so far we've been focused mainly on "read", some discussion about "create"). cc @m-nash @srnagar @joheredi @johanste @lmazuel .

This does also tie into an issue I'm looking into, which is what model we want for a given content type (https://github.com/Azure/cadl-azure/issues/2451). I want to see how we can better incorporate visibility into this helper function as well. Going to spend some time going over this tomorrow. Thanks for the great question!

**Comment by changlong-liu** [comment]
> Hi @lmazuel, also for models/visibility case, it has routing unmatch issue, but I saw you created pr to add this case into python and the tests passed. I am curious on why the tests can pass. Will the tests pass if url is updated?
> 
> PR: [Azure/autorest.python#1630](https://github.com/Azure/autorest.python/pull/1630)

Hi @haolingdong-msft , for `visibility`, current released `cadl-ranch-specs@0.6.2` doesn't have the url mis-match issue. So it works in autorest.python. 
But I'm also wondering the mismatch in latest cadl-ranch main branch is a problem, so I created a PR for it: https://github.com/Azure/cadl-ranch/pull/192

**Comment by changlong-liu** [comment]
For `projection`, that should be because the `producedBy` have been projected its' json name to `codegen`. https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/projection/main.cadl#L13

**Comment by haolingdong-msft** [comment]
close this issue as the route related bugs are fixed. Java is discussing about how to support visibility model case in this issue: https://github.com/Azure/autorest.java/issues/1954
