### ISSUE TITLE
validation not picking up an import error

### ISSUE THREAD

**Issue by iscai-msft** [Azure/cadl-ranch#232]
When I switched the cadl specs over to using the typespec packages, one of the changes was using the new `@typespec/http` library (which was split from the `@typespec/rest` library. Validation didn't catch my incorrect imports (I was still importing from the rest library, but using the Http namespace) and I had to make the [following changes](https://github.com/Azure/cadl-ranch/pull/231) once released.

I tried to debug into validation but couldn't figure out why validation didn't catch this issue.

**Comment by timotheeguerin** [comment]
I guess it not failing is expected as the rest library import the http so you do import it indirectly. Not sure what was the issue in the end.
