### ISSUE TITLE
[DPG] Support of Record<unknown> in models 

### ISSUE THREAD

**Issue by lmazuel** [Azure/cadl-ranch#251]
`Record<unknown>` means any JSON object, but not JSON token. You can pass anything like `{...}`, but not an array of string or null.

It may or may not makes sense to separate this scenario from `unknown` which is more wide

Tests should include a JSON object, input output

**Comment by tadelesh** [comment]
Already exists one here: https://github.com/Azure/cadl-ranch/blob/34be94ff4a86e485862786382ba0c56e1db63da2/packages/cadl-ranch-specs/http/type/dictionary/main.tsp#L84

**Comment by tadelesh** [comment]
Test is covered by Record<unknow> from dictionary test and Record property from model property test.
