### ISSUE TITLE
Add tests for the repeatability headers

### ISSUE THREAD

**Issue by lirenhe** [Azure/cadl-ranch#327]
This is a place holder for the support of repeatability headers when we have the design ready for this feature.

This is the updated guideline:
https://azure.github.io/azure-sdk/general_design.html#repeatable-requests

**Comment by weidongxu-microsoft** [comment]
Test may involve mockapi return a few 500 before 200, meanwhile verify these client retries have same request-id and first-sent.

Another test would let client send it with a given request-id and first-sent (as from customer).

**Comment by tadelesh** [comment]
Resolved in: https://github.com/Azure/cadl-ranch/pull/348
