### ISSUE TITLE
[Mockapi][Feature] `mockapi` supports `res`

### ISSUE THREAD

**Issue by msyyc** [Azure/cadl-ranch#36]
Compared with [mockapi](https://github.com/Azure/cadl-ranch/blob/1dbe0df3c5e2c6a20a3fb60fe1e197d98efeae37/packages/cadl-ranch-specs/http/from-testserver/non-string-enum/mockapi.ts#L7), [router](https://github.com/Azure/autorest.testserver/blob/e66f072497164e23886e40ac687774333b8d3671/legacy/routes/nonStringEnums.js#L11) of autorest.testserver support `res` which could make the test more compact and clean. If we could support it, it will be very convenient.

**Comment by timotheeguerin** [comment]
Could you explain more how this make it cleaner, the mockapi style was done with the very purpose of not having to use the express response which require a lot more knowledge of how to use express.

**Comment by msyyc** [comment]
https://github.com/Azure/cadl-ranch/blob/1dbe0df3c5e2c6a20a3fb60fe1e197d98efeae37/packages/cadl-ranch-specs/http/from-testserver/non-string-enum/mockapi.ts#L9
![image](https://user-images.githubusercontent.com/70930885/183844670-6bfa8d7d-2a21-4b31-a0ab-abc6a569ff52.png)

https://github.com/Azure/autorest.testserver/blob/e66f072497164e23886e40ac687774333b8d3671/legacy/routes/nonStringEnums.js#L15

I think we could provide some response template which makes the mockapi cleaner like:

**Comment by timotheeguerin** [comment]
there is a few helpers, in particular `json` will set a json body so you don't have to manually write the content type.
```
 return {
      status: 200,
      body: json({ received: "model" }),
    };
```
