### ISSUE TITLE
Add coverage for custom LRO RPC

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/cadl-ranch#372]
We should have coverage for LRO RPC operations that follow a similar format to what Health Insights supports. 

Link to the TypeSpec: [link](https://github.com/Azure/azure-rest-api-specs-pr/blob/6ebbbe44640bb2145789b72d7a8b87ffa92a0f0a/specification/cognitiveservices/HealthInsights/healthinsights.common/primitives.tsp)

Custom LRO RPC template: 
```
@doc("Long running RPC operation template")
@post
op TLongRunningRpcOperation<
  TParams,
  TResponse
> is Azure.Core.Foundations.Operation<
  TParams & RepeatabilityRequestHeaders,
  (Foundations.AcceptedResponse<Foundations.LongRunningStatusLocation<TResponse> &
    Foundations.RetryAfterHeader> &
    RepeatabilityResponseHeaders),
  RepeatabilityRequestHeaders & RepeatabilityResponseHeaders,
  Azure.Core.Foundations.ErrorResponse
>;
```

Link to operation defintion: [link](https://github.com/Azure/azure-rest-api-specs-pr/blob/6ebbbe44640bb2145789b72d7a8b87ffa92a0f0a/specification/cognitiveservices/HealthInsights/healthinsights.oncophenotype/route.oncophenotype.tsp#L46C3-L46C81)

LRO RPC template usage:
```
op createJob is TLongRunningRpcOperation<OncoPhenotypeData, OncoPhenotypeResult>;
```

Health Insights LRO behavior: 
1. Initial POST request to the service with input data in `OncoPhenotypeData`.
2. 202 response returned with `Operation-Location` header, as well as repeatability and retry headers, no body. 
3. Poll at `Operation-Location` url.
4. Receive 200 response with final payload `OncoPhenotypeResult`.

**Comment by weidongxu-microsoft** [comment]
We've had it here https://github.com/Azure/cadl-ranch/pull/342
But it is not fully reviewed by Mark.

The template in cadl-ranch lro/rpc/legacy mostly reflect the runtime behavior, except the `| TResponse` in the last line of
```ts
    Foundations.AcceptedResponse<{
      @pollingLocation
      @doc("The location for monitoring the operation state.")
      @TypeSpec.Http.header("Operation-Location")
      operationLocation: TypeSpec.Rest.ResourceLocation<TPollResponse>;
    } & Foundations.RetryAfterHeader> | TResponse
```

It kind of follow a traditional solution in Swagger, that adding an additional 200 with the "logical result" or "final result". But service never return 200 in that POST.

I think removing that `| TResponse` would still work. Mark's helper function would take the poll result as logical result, when not finding that 200.

---

PS: Mike had a "final-state-schema" in Swagger that will get rid of the extra 200.
https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-long-running-operation-options

But it may take time to get adopted.
