### ISSUE TITLE
[bug] `pnpm validate-mock-apis` will alway report errrors

### ISSUE THREAD

**Issue by archerzz** [Azure/cadl-ranch#382]
## Description

On my local environment, when I run `pnpm validate-mock-apis` at the root folder of the `cadl-ranch` repository, it will report scenario missing mockapi file error on every spec. But on the build pipeline, `Validate Mock apis` step can correctly report error.

See my pr #381, in previous commit, it contains some mismatch of scenario names. After fixing those errors, the pipeline is green, but running `pnpm validate-mock-apis` will still give me errors like below:
```powershell
info: Found 38 scenarios.
error: ✘ Scenario special-words is missing a mockapi file. Make sure to have a mockapi.ts that is built.
error: ✘ Scenario type/union is missing a mockapi file. Make sure to have a mockapi.ts that is built.
error: ✘ Scenario type/dictionary is missing a mockapi file. Make sure to have a mockapi.ts that is built.
error: ✘ Scenario type/array is missing a mockapi file. Make sure to have a mockapi.ts that is built.
error: ✘ Scenario special-headers/repeatability is missing a mockapi file. Make sure to have a mockapi.ts that is built.
error: ✘ Scenario special-headers/client-request-id is missing a mockapi file. Make sure to have a mockapi.ts that is built.
error: ✘ Scenario resiliency/srv-driven is missing a mockapi file. Make sure to have a mockapi.ts that is built.
error: ✘ Scenario projection/projected-name is missing a mockapi file. Make sure to have a mockapi.ts that is built.
...
```

**Comment by timotheeguerin** [comment]
Which OS are you on? wondering if maybe we have a path compare issue

**Comment by archerzz** [comment]
> Hey @archerzz could you confirm this is resolving your issues on windows #383

@timotheeguerin I confirmed that the PR fixed this issue. Thanks!
