### ISSUE TITLE
Fix: Mock api implementation [from-testserver]

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/cadl-ranch#40]
Seems like mock apis are invalid(don't pass the test. I didn't wire the CI correctly so it wasn't validating)

Update here when added the test https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch/src/actions/validate-mock-apis.ts#L90

[Docs for writing mock apis](https://github.com/Azure/cadl-ranch/blob/main/docs/writing-mock-apis.md)

Use `npm run validate-mock-apis` to check everything is good or the errors(Remove the exluded line first)
Invalid mock apis:
- [ ]  `from-testserver/non-string-enum`
- [ ]  `from-testserver/extensible-enums`

Other item
- [ ] Can those specs also be renamed. `from-testserver` is irrelevant. They supposed to described scenarios.

**Comment by msyyc** [comment]
Hi @timotheeguerin, I fixed the mockapi of my part: https://github.com/Azure/cadl-ranch/pull/43. 
As for the folder name `from-testserver`, my thought is that `xxx.json` in autorest.testserver correspond with `from-testserver/xxx/main.cadl` so that language owners can use the existing testcase of codegen to test instead of writing new test which can save a lot of effort. What's more, the translation is easier than creating a new scenario.

**Comment by timotheeguerin** [comment]
Thanks for fixing those, yeah I don't know, one of the goal I had when making this was to repeat the meaningless value of the testserver test cases and have scenarios be meaningful scenarios. i.e. given a dashboard of all the scenarios someone can understand what is being supported and what isn't by each generator and lot of the test server test are just smoke test not describing expected behavior.

In those test for example some scenario names don't make much sense like what does `addPet` has to do with non extensible enums? What this really is testing is that you can have extensibve enums inside model and the scenario name and scenario doc should reflect that.

**Comment by msyyc** [comment]
Got it. I add some detailed description to make the  testcase more clear. Please review: https://github.com/Azure/cadl-ranch/pull/46

**Comment by iscai-msft** [comment]
@msyyc I don't think it's a good idea to have `from-testserver`. We don't want to be tied down by what the testserver had, we want to be better than the autorest.testserver. Are you ok if we close and remove the `from-testserver` folder? We want to make sure all of the contributions fulfill [this checklist](https://github.com/Azure/cadl-ranch/blob/main/.github/pull_request_template.md#cadl-ranch-contribution-checklist) and the testserver tests don't. Thanks!

**Comment by msyyc** [comment]
> @msyyc I don't think it's a good idea to have `from-testserver`. We don't want to be tied down by what the testserver had, we want to be better than the autorest.testserver. Are you ok if we close and remove the `from-testserver` folder? We want to make sure all of the contributions fulfill [this checklist](https://github.com/Azure/cadl-ranch/blob/main/.github/pull_request_template.md#cadl-ranch-contribution-checklist) and the testserver tests don't. Thanks!

Got it and please review: https://github.com/Azure/cadl-ranch/pull/66
