### ISSUE TITLE
Add validation to ban use of `Azure.` namespace outside of the Azure folder

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/cadl-ranch#418]
Anything azure specific should be contained in that folder the rest should be pure typespec with http

**Comment by lirenhe** [comment]
@sarangan12, as you are working on the refactoring of cadl-ranch cases,  feel free to close this if this effort is tracked somewhere else

**Comment by sarangan12** [comment]
With the recent refactoring of `cadl-ranch` packages, now the entire folder structure has been changed to 2 packages:

1. `@typespec/http-specs` (https://github.com/microsoft/typespec/tree/main/packages/http-specs) - Pure Typespec Scenarios
2. `@azure-tools/azure-http-specs` (https://github.com/Azure/typespec-azure/tree/main/packages/azure-http-specs)  - Azure Typespec scenarios

The pure typespec scenarios do not even have azure dependencies and will continue the same design. With this restructure, I believe this issue can be resolved. Closing this issue. Thanks.
