### ISSUE TITLE
Pipeline shows green when one package fails to publish

### ISSUE THREAD

**Issue by m-nash** [Azure/cadl-ranch#441]
We should probably mark the pipeline as failed if a package fails to publish

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3159202&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=c3091b1e-314e-512e-11db-151fdba14cd6&l=680

**Comment by timotheeguerin** [comment]
This is by design, we only publish packages with a new version, that version already existed because that bump bug happened before.
