### ISSUE TITLE
Add test for support of union with consistent type as extensible enum

### ISSUE THREAD

**Issue by lmazuel** [Azure/cadl-ranch#446]
In particular this:
```typescript
union KnownErrorCode {
  // This is not found
  "NotFound",
  InvalidName: "Invalid",
  string
} 
```

should generate an extensible enum once https://github.com/Azure/typespec-azure/issues/3813 is done.

Was discussed with @johanste and @bterlson 

[Full picture on Loop](https://microsoft.sharepoint.com/:fl:/s/d40daadc-c0b7-46ef-8088-d7b3a5bad5f8/EYXTfObxOKJCodhiChGfJ-ABHlnWX1a4fBuwK2YkXa2KIA?e=8mVnB5&nav=cz0lMkZzaXRlcyUyRmQ0MGRhYWRjLWMwYjctNDZlZi04MDg4LWQ3YjNhNWJhZDVmOCZkPWIlMjE1LW9vVDlZZjJrZU1qNE8xT1JQdmJ2NTBieVRvNjd0SWdHSC1xOHA0dmFISkRTcUR1eHVyU2F0WU9IT3pfT1VJJmY9MDFLS09FQ1k0RjJONk9ONEpZVUpCS0RXRENCSUlaNko3QSZjPSUyRiZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUUxTFc5dlZEbFpaakpyWlUxcU5FOHhUMUpRZG1KMk5UQmllVlJ2TmpkMFNXZEhTQzF4T0hBMGRtRklTa1JUY1VSMWVIVnlVMkYwV1U5SVQzcGZUMVZKZkRBeFMwdFBSVU5aTjFoYU5FRTNRVFZHV1ZKR1FqTkJWRlUzVUVOSlVqVTJURVElM0QlMjIlMkMlMjJpJTIyJTNBJTIyYmQ3ZDFhNzMtOGI2Ni00YTg5LWEyMTMtOTI5MDQxODIxMzFlJTIyJTdE)

**Comment by timotheeguerin** [comment]
I have a pr in progress redesigning the unions test cases #429 this should be covered there
