### ISSUE TITLE
Serve should fail when different scenarios have same uri

### ISSUE THREAD

**Issue by pshao25** [Azure/cadl-ranch#51]
We could start `cadl-ranch serve ./http` when different scenrios have same uri now. e.g., 
https://github.com/Azure/cadl-ranch/blob/c4f41f483eac812527f7b6dc837bd22d255a18ed/packages/cadl-ranch-specs/http/resiliency/srv-driven-1/mockapi.ts#L16
https://github.com/Azure/cadl-ranch/blob/c4f41f483eac812527f7b6dc837bd22d255a18ed/packages/cadl-ranch-specs/http/resiliency/srv-driven-2/mockapi.ts#L16

I think we should fail this.

**Comment by haolingdong-msft** [comment]
There is also the same problem with tests under /models folder,all operations under models/ folder defined route as "/models", e.g. https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/collections-basic/main.cadl#L47, https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/collections-models/main.cadl#L35,  this can also lead to all the operations have the same url and have problem in finding the corresponding operation.

**Comment by weidongxu-microsoft** [comment]
For cadl under "models" folder, should we just use different routes in different test scenarios?

**Comment by timotheeguerin** [comment]
Yeah I agree, there shouldn't be any duplicated endpoint. The rule right now is 1 scenario to 1 or more endpoints(for things like paging lro). But either way each endpoint should be completely unique. I'll add some validation to the mock server.

**Comment by pshao25** [comment]
What's more, we also need to fail when two scenarios have the same name.

**Comment by timotheeguerin** [comment]
Agree on scenario name duplicate as well. Have a PR adding validation and doing a rough fix to make it pass https://github.com/Azure/cadl-ranch/pull/58
