### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by msyyc** [Azure/cadl-ranch#53]
[ validateBodyEquals](https://github.com/Azure/cadl-ranch/blob/c4f41f483eac812527f7b6dc837bd22d255a18ed/packages/cadl-ranch-api/src/request-validations.ts#L24-L35) and [validateCoercedDateBodyEquals](https://github.com/Azure/cadl-ranch/blob/c4f41f483eac812527f7b6dc837bd22d255a18ed/packages/cadl-ranch-api/src/request-validations.ts#L37-L48) have same content

**Comment by timotheeguerin** [comment]
Seems like the same is in the autorest.testserver then. I really dislike the coerced functionality that was there before. Is this really needed for comparing the dates. THis feels like a bad hack.

**Comment by lmazuel** [comment]
Closing as this is not really a problem, and could be fixed later
