### ISSUE TITLE
MFD `jsonArrayParts` case is not aligned with typespec definition

### ISSUE THREAD

**Issue by MaryGao** [Azure/cadl-ranch#570]
In typespec [def](https://github.com/timotheeguerin/typespec/blob/5a9ffa2434f5c1add5a9e373d06f438614c6004e/docs/libraries/http/multipart.md#examples) for `addresses` it should have N parts for N addresses, not 1 part for an array of addresess.

```
// Send multiple fields - In this scenario each address is sent as an individual part
model Address {
  street: string;
  city: string;
}
op create(@header contentType: "multipart/form-data", addresses: Address[]): void;
```
So the current case implementation is not aligned with typespec definition
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/payload/multipart/main.tsp#L231-L242

**Comment by msyyc** [comment]
There is already typespec design for this case https://github.com/microsoft/typespec/issues/3046 however it is not implemented yet. And for now there is no service for this scenario, so we will not update the case until there is new requirement. If language emitter has not passed the case, please hold it on.

**Comment by lmazuel** [comment]
@MaryGao is right that the test is not implemented as it should. If should be N part of one object:

```
model Something {
   id: Obj1 // one part, one obj
   adress[]: // N parts, one obj
   adress[][]: // N parts, array of object
}
```

This is the default semantic. For more advanced scenario, we need #3046, but the default behavior is as described here.
