### ISSUE TITLE
Returned 400 for query explode=true case with path explode/array?param=a&param=b

### ISSUE THREAD

**Issue by MaryGao** [Azure/cadl-ranch#731]
When we integrated with the query explode case we receive the 400 error with path: http://localhost:3000/routes/query/query-expansion/explode/array?param=a&param=b.

case: https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/routes/main.tsp#L401
![{2662644B-BB6D-4507-B434-E541A659CB85}](https://github.com/user-attachments/assets/c5cd3d4b-0ff6-4579-b23d-ddcfefd9684b)

**Comment by timotheeguerin** [comment]
Mock api probably need to be updated. Seems like express might join back those with comma which is weird

**Comment by timotheeguerin** [comment]
Mock api probably just wrong and need to expect all the values
