### ISSUE TITLE
bug in templated case

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/cadl-ranch#733]
There is no `kind` property in `NumericType<int32>`

https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/model/templated/main.tsp#L44-L71

```
com.azure.core.exception.HttpResponseException: Status code 400, "{"message":"Body provided doesn't match expected body","expected":{"kind":"Int32Values","values":[1234],"value":1234},"actual":{"values":[1234],"value":1234}}"
```

**Comment by melina5656** [comment]
After discussion, we believe that this test case is not suitable to be added. we have removed it. So close this issue.
