### ISSUE TITLE
mock value not correct in /duration operation in models/property-types 

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/cadl-ranch#90]
Hi @iscai-msft / @timotheeguerin ,
I found in below cadl definition, /duration operation's input model is 'zonedDateTime'. 
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/property-types/main.cadl#L91

But the mockapi value is 'P123DT22H14M12.011S' which cannot be mappedto 'zonedDateTime'. Our code will throw error when trying to map 'P123DT22H14M12.011S' to Java type `OffsetDateTime`.
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/property-types/mockapi.ts#L58

I guess cadl file should be modified. I created a pr to fix, please take a look. https://github.com/Azure/cadl-ranch/pull/89

**Comment by iscai-msft** [comment]
fixed by #89
